# Tutorial Clustering - k-nearest neighbor

In this tutorial you will learn the basics about clustering with k-nearest neighbor method.

## Contents of the tutorial

1. Explanation of k-nearest neighbor method
2. Step-by-step programming k-nearest neighbor method
    - Libraries <br>
Step 1. Importing dataset <br>
Step 2. Function Euclidean distance<br>
Step 3. Function KNN<br>
Step 3a. Euclidean distance<br>
Step 3b. Sorting<br>
Step 3c. Take the top k neighbors<br>
Step 3d. Most frequent class<br>
Step 4. Define test set<br>
Step 5. Define k<br>
Step 6. Let KNN model run<br>

_________________________

### 1. Explanation of k-nearest neighbor method

K-nearest neighbor (KNN) is mostly used for regression and classification. It is a supervised algorithm. It is good in three things:
- It has an easy interpretable output. 
- It has a short calculation time. 
- It is good at predictions. 

First, we’ll show an easy example. (Example and explanation from: https://www.analyticsvidhya.com/blog/2018/03/introduction-k-neighbours-algorithm-clustering/) 

We have 3 red circles, 3 green squares and a blue star. We want to know the classification of the blue star. This will be red circles or green squares. Take k as the number of neighbors. In this case we’ll take k = 3. Now we draw a circle around the blue star, in such a way that there are exactly 3 datapoints in the circle. We can see that there are only red circles in the circle, and thus the blue star belongs to the red circles.  

<img src="Ex_cl_KNN1.PNG" width=500/>
<img src="Ex_cl_KNN2.PNG" width=500/>

An important thing is of course, the value of k. Small values will cause the noise to have a higher influence on the result, but a high value will make it hard to compute. The simplest way to choose it is $k = \sqrt{n}$, with n the number of datapoints in the dataset.  

Down below another method is explained. It takes the shortest Euclidean distance to see which neighobrs are the closest. Nextly, it determines the most occuring class. Then it checks whether this class is right. When this is tried out for several classes, you can determine which is best.

In this tutorial we use Euclidean distance, but several kinds of distances can be used.

#### Euclidean distance

Take the square root of the sum of the squares of the difference of the coordinates.
For example: $x=(a,b)$ and $y=(c,d)$ then the Euclidean distance is $\sqrt{{(a-c)}^2+{(b-d)}^2}$

#### Manhattan distance

Take the sum of the absolute values of the differences of the coordinates.
For example: $x=(a,b)$ and $y=(c,d)$ then the Manhattan distance is $|a-c| + |b-d|$

#### Minkowski distance

This is actually the most general form.
The formula is $D = \sqrt[p]{\sum_{k=1}^{n} {|x-y|}^p}$.
When p = 1, you use Manhattan distance, when p = 2, you use Euclidean distance.

______________________

### 2. Step-by-step programming k-nearest neighbor clustering

#### Libraries

For k-nearest neighbor clustering the following libraries are needed:

- Numpy
- Pandas
- Math
- Operator

Import them in the cell below.

In [2]:
## Import the libraries here
import numpy as np
import pandas as pd
import math
import operator

#### Step 1. Importing dataset

ik moet nog een dataset maken die in de map staat
A dataset is needed which contains numbers and at least two different classes assigned to these point. We will divide this set into two parts: one (test set) which you are going to use to determine the class of the other one (training set).
Import the dataset ... in the cell below using pandas.

In [4]:
## Import the dataset here

data = pd.DataFrame ({
    'x': [12, 20, 28, 18, 29, 33, 24, 45, 45, 52, 51, 52, 55, 53, 55, 61, 64, 69, 72, 72, 70, 79, 68, 65],
    'y': [39, 36, 30, 52, 54, 46, 55, 59, 63, 70, 66, 63, 58, 23, 14, 8, 19, 7, 24, 42, 45, 62, 55, 59],
    'class': ['A', 'A', 'B', 'B', 'A', 'B', 'C', 'C', 'A', 'A', 'B', 'B', 'A', 'B', 'C', 'C','A', 'A', 'B', 'B', 'A', 'B', 'C', 'C',]
})
data

   class   x   y
0      A  12  39
1      A  20  36
2      B  28  30
3      B  18  52
4      A  29  54
5      B  33  46
6      C  24  55
7      C  45  59
8      A  45  63
9      A  52  70
10     B  51  66
11     B  52  63
12     A  55  58
13     B  53  23
14     C  55  14
15     C  61   8
16     A  64  19
17     A  69   7
18     B  72  24
19     B  72  42
20     A  70  45
21     B  79  62
22     C  68  55
23     C  65  59

#### Step 2. Function Euclidean distance

In the cell, make a function which determines the Euclidean distance between two points. Make it as a for-loop.<span style="color:red"> Hier kwam ik niet uit. ik heb naar het antwoord gekeken, maar ik zie dat het antwoord nog niet is gekoppeld met de dataset. misschien dit toevoegen </span>

In [13]:
## Make function Euclidean distance

def EuclideanDistance(data1, data2, length):
    distance = 0
    for x in range(length):
        distance += np.square(data1[x] - data2[x])
    return np.sqrt(distance)

#### Step 3. Function KNN

The next four steps will make a function for k-nearest neighbor clustering. Down below you can make the entire function.

So firstly make the function.

##### Step 3a. Euclidean distance

Use the function you have made for the calculation of the Euclidean distance to determine the distance the points of the training set and the points of the test set. Add this as a column to the dataframe.

##### Step 3b. Sorting

For each point of the training set, sort the distances in descending order.

##### Step 3c. Take the top k neighbors

Take the top k neighbors, so the k-nearest neighbors.

##### Step 3d. Most frequent class

See which class is most frequent for each point of the training set, and define this class as the class of the point.

In [14]:
## Make function KNN
## Make function KNN

def KNN(TrainingSet, TestSet, k):
    # Create sets for distances, sorted and the length
    distances = {}
    sort = {}
    
    length = TestSet.shape[1]
    
    # Step 3a.: use EuclideanDistance function 
    for x in range(len(TrainingSet)):
        dist = EuclideanDistance(TestSet, TrainingSet.iloc[x], length)
        
        distances[x] = dist[0]
    
    # Step 3b.: sorting
    sorted_d = sorted(distances.items(), key=operator.itemgetter(1))
    
    neighbors = []
    
    # Step 3c.: take top k neighbors
    for x in range(k):
        neighbors.append(sorted_d[x][0])
    
    classVotes = {}
    
    # Step 3d.: most frequent class
    for x in range(len(neighbors)):
        response = TrainingSet.iloc[neighbors[x][-1]]
        
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)
    return(sortedVotes[0][0], neighbors)

#### Step 4. Define test set

Define which points of the dataset are the test set.

In [15]:
## Define the test set

testSet = [[18, 52, 70, 65]]
test = pd.DataFrame(testSet)
test

    0   1   2   3
0  18  52  70  65

#### Step 5. Define k

Define the value of k. For the first iteration, start with k = 1.

In [11]:
## Define k

k=1

#### Step 6. Let KNN model run for multiple k

Let the model run for various values of k, to see which value is the best. <span style="color:red"> De code werkt niet, dus ik heb nog niet echt een beeld bij wat ik nu precies heb gedaan </span>

In [12]:
## Let KNN model run

result,neigh = KNN(data, test, k)

TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')